const fs = require('fs');
let text = fs.readFileSync('src/components/AntiUninstallProtectionCard.tsx', 'utf-8');

// The issue is with constructs like: translateInline(lang, 'English', '${translateInline(lang, 'English', 'Arabic')}')
// Because there might be nested quotes. Let's do a more robust replace.

text = text.replace(/translateInline\(lang, '([^']+)', '\$\{translateInline\(lang, '([^']+)', '([^']+)'\)\}'\)/g, "translateInline(lang, '$2', '$3')");
text = text.replace(/translateInline\(lang, '([^']+)', '\$\{translateInline\(lang, "([^"]+)", '([^']+)'\)\}'\)/g, "translateInline(lang, '$2', '$3')");

// Also, some have single quotes inside, which broke the AST so my regex didn't work.
// E.g. '${translateInline(lang, 'Bound to DroidGuardDeviceAdminReceiver to disable Android 'Uninstall' button.', 'مربوط بمكون ...')}'
// Let's replace the raw broken strings.
text = text.replace(/\{translateInline\(lang, 'Device Admin Policy:', '\$\{translateInline\(lang, 'Device Admin Unit \(DevicePolicyManager\):', 'وحدة مدير الجهاز \(DevicePolicyManager\):'\)\}'\)\}/g, "{translateInline(lang, 'Device Admin Unit (DevicePolicyManager):', 'وحدة مدير الجهاز (DevicePolicyManager):')}");
text = text.replace(/\{translateInline\(lang, 'Bound to DroidGuardDeviceAdminReceiver preventing the OS "Uninstall" button\.', '\$\{translateInline\(lang, 'Bound to DroidGuardDeviceAdminReceiver to disable Android 'Uninstall' button\.', 'مربوط بمكون DroidGuardDeviceAdminReceiver لمنع زر "إلغاء التثبيت" في نظام أندرويد من العمل\.'\)\}'\)\}/g, "{translateInline(lang, 'Bound to DroidGuardDeviceAdminReceiver to disable Android \"Uninstall\" button.', 'مربوط بمكون DroidGuardDeviceAdminReceiver لمنع زر \"إلغاء التثبيت\" في نظام أندرويد من العمل.')}");
text = text.replace(/\{translateInline\(lang, 'Biometric Auth Unit:', '\$\{translateInline\(lang, 'Biometric Auth \(expo-local-authentication\):', 'التحقق البيومتري \(expo-local-authentication\):'\)\}'\)\}/g, "{translateInline(lang, 'Biometric Auth (expo-local-authentication):', 'التحقق البيومتري (expo-local-authentication):')}");
text = text.replace(/\{translateInline\(lang, 'Enforces fingerprint, face ID, or system PIN on any deactivation attempt\.', '\$\{translateInline\(lang, 'Requires Fingerprint, Face ID, or system PIN for any deactivation attempt\.', 'يشترط بصمة الإصبع، التعرف على الوجه، أو PIN النظام لأي محاولة تعطيل أو خروج\.'\)\}'\)\}/g, "{translateInline(lang, 'Requires Fingerprint, Face ID, or system PIN for any deactivation attempt.', 'يشترط بصمة الإصبع، التعرف على الوجه، أو PIN النظام لأي محاولة تعطيل أو خروج.')}");

text = text.replace(/\{translateInline\(lang, 'Deactivate Admin \(Requires Biometrics\)', '\$\{translateInline\(lang, 'Deactivate Protection \(Biometrics Required\)', 'تعطيل الحماية \(يتطلب التحقق البيومتري\)'\)\}'\)\}/g, "{translateInline(lang, 'Deactivate Protection (Biometrics Required)', 'تعطيل الحماية (يتطلب التحقق البيومتري)')}");
text = text.replace(/\{translateInline\(lang, 'Activate Anti-Uninstall Protection', '\$\{translateInline\(lang, 'Activate Anti-Uninstall Protection Now', 'تفعيل حماية إلغاء التثبيت الآن'\)\}'\)\}/g, "{translateInline(lang, 'Activate Anti-Uninstall Protection Now', 'تفعيل حماية إلغاء التثبيت الآن')}");

text = text.replace(/\{translateInline\(lang, '⚡ Simulate Android Settings Uninstall Attempt', '\$\{translateInline\(lang, '⚡ Simulate Uninstall Attempt from Android Settings', '⚡ محاكاة محاولة إلغاء التثبيت من إعدادات أندرويد'\)\}'\)\}/g, "{translateInline(lang, '⚡ Simulate Uninstall Attempt from Android Settings', '⚡ محاكاة محاولة إلغاء التثبيت من إعدادات أندرويد')}");
text = text.replace(/\{translateInline\(lang, 'Do you want to uninstall DroidGuard\?', '\$\{translateInline\(lang, 'Do you want to uninstall DroidGuard\?', 'هل تريد إلغاء تثبيت تطبيق DroidGuard\?'\)\}'\)\}/g, "{translateInline(lang, 'Do you want to uninstall DroidGuard?', 'هل تريد إلغاء تثبيت تطبيق DroidGuard؟')}");
text = text.replace(/\{translateInline\(lang, 'Simulating thief pressing Uninstall in Android Apps Settings\.', '\$\{translateInline\(lang, 'Simulation of thief or intruder pressing uninstall button in phone settings\.', 'محاكاة لضغط السارق أو المتطفل على زر إلغاء التثبيت داخل إعدادات الهاتف\.'\)\}'\)\}/g, "{translateInline(lang, 'Simulation of thief or intruder pressing uninstall button in phone settings.', 'محاكاة لضغط السارق أو المتطفل على زر إلغاء التثبيت داخل إعدادات الهاتف.')}");

text = text.replace(/\{translateInline\(lang, 'Cannot Uninstall Package', '\$\{translateInline\(lang, 'Cannot Uninstall \(Device Admin Block\)', 'تعذر إلغاء التثبيت \(Device Admin Block\)'\)\}'\)\}/g, "{translateInline(lang, 'Cannot Uninstall (Device Admin Block)', 'تعذر إلغاء التثبيت (Device Admin Block)')}");
text = text.replace(/\{translateInline\(lang, '⚠️ DroidGuard cannot be uninstalled because it is currently an active Device Administrator\.', '\$\{translateInline\(lang, '⚠️ DroidGuard cannot be uninstalled because it is an active Device Administrator\.', '⚠️ لا يمكن إلغاء تثبيت DroidGuard لأن التطبيق مفعل كمدير لجهاز أندرويد \(Device Administrator\)\.'\)\}'\)\}/g, "{translateInline(lang, '⚠️ DroidGuard cannot be uninstalled because it is an active Device Administrator.', '⚠️ لا يمكن إلغاء تثبيت DroidGuard لأن التطبيق مفعل كمدير لجهاز أندرويد (Device Administrator).')}");
text = text.replace(/\{translateInline\(lang, 'To proceed, you must deactivate Device Admin first, which enforces mandatory biometric verification\.', '\$\{translateInline\(lang, 'To uninstall, you must deactivate Device Admin first, which requires mandatory biometrics \(Fingerprint, Face, or PIN\)\.', 'لمتابعة إلغاء التثبيت، يجب إلغاء تفعيل صلاحية مدير الجهاز أولاً، وهو ما يتطلب اجتياز التحقق البيومتري الإلزامي \(بصمة الإصبع أو الوجه أو PIN المالك\)\.'\)\}'\)\}/g, "{translateInline(lang, 'To uninstall, you must deactivate Device Admin first, which requires mandatory biometrics (Fingerprint, Face, or PIN).', 'لمتابعة إلغاء التثبيت، يجب إلغاء تفعيل صلاحية مدير الجهاز أولاً، وهو ما يتطلب اجتياز التحقق البيومتري الإلزامي (بصمة الإصبع أو الوجه أو PIN المالك).')}");
text = text.replace(/translateInline\(lang, 'Deactivate Device Admin to permit uninstallation', '\$\{translateInline\(lang, 'Request deactivation of Device Admin for uninstall attempt', 'طلب إلغاء صلاحية مدير الجهاز لمحاولة إلغاء التثبيت'\)\}'\)/g, "translateInline(lang, 'Request deactivation of Device Admin for uninstall attempt', 'طلب إلغاء صلاحية مدير الجهاز لمحاولة إلغاء التثبيت')");

fs.writeFileSync('src/components/AntiUninstallProtectionCard.tsx', text);
