const fs = require('fs');
let text = fs.readFileSync('src/components/AntiUninstallProtectionCard.tsx', 'utf-8');

text = text.replace(/\{translateInline\(lang, 'Cannot Uninstall Package', '\$\{translateInline\(lang, 'Cannot Uninstall \(Device Admin Block\)', 'تعذر إلغاء التثبيت \(Device Admin Block\)'\)\}'\)\}/g, "{translateInline(lang, 'Cannot Uninstall (Device Admin Block)', 'تعذر إلغاء التثبيت (Device Admin Block)')}");
text = text.replace(/\{translateInline\(lang, '⚠️ DroidGuard cannot be uninstalled because it is currently an active Device Administrator.', '\$\{translateInline\(lang, '⚠️ DroidGuard cannot be uninstalled because it is an active Device Administrator.', '⚠️ لا يمكن إلغاء تثبيت DroidGuard لأن التطبيق مفعل كمدير لجهاز أندرويد \(Device Administrator\).'\)\}'\)\}/g, "{translateInline(lang, '⚠️ DroidGuard cannot be uninstalled because it is an active Device Administrator.', '⚠️ لا يمكن إلغاء تثبيت DroidGuard لأن التطبيق مفعل كمدير لجهاز أندرويد (Device Administrator).')}");
text = text.replace(/\{translateInline\(lang, 'To proceed, you must deactivate Device Admin first, which enforces mandatory biometric verification.', '\$\{translateInline\(lang, 'To uninstall, you must deactivate Device Admin first, which requires mandatory biometrics \(Fingerprint, Face, or PIN\).', 'لمتابعة إلغاء التثبيت، يجب إلغاء تفعيل صلاحية مدير الجهاز أولاً، وهو ما يتطلب اجتياز التحقق البيومتري الإلزامي \(بصمة الإصبع أو الوجه أو PIN المالك\).'\)\}'\)\}/g, "{translateInline(lang, 'To uninstall, you must deactivate Device Admin first, which requires mandatory biometrics (Fingerprint, Face, or PIN).', 'لمتابعة إلغاء التثبيت، يجب إلغاء تفعيل صلاحية مدير الجهاز أولاً، وهو ما يتطلب اجتياز التحقق البيومتري الإلزامي (بصمة الإصبع أو الوجه أو PIN المالك).')}");
text = text.replace(/translateInline\(lang, 'Deactivate Device Admin to permit uninstallation', '\$\{translateInline\(lang, 'Request deactivation of Device Admin for uninstall attempt', 'طلب إلغاء صلاحية مدير الجهاز لمحاولة إلغاء التثبيت'\)\}'\)/g, "translateInline(lang, 'Request deactivation of Device Admin for uninstall attempt', 'طلب إلغاء صلاحية مدير الجهاز لمحاولة إلغاء التثبيت')");
text = text.replace(/translateInline\(lang, 'Android Biometric Prompt • Mandatory Authentication', '\$\{translateInline\(lang, 'Android Biometric Prompt • Mandatory Biometrics', 'Android Biometric Prompt • التحقق البيومتري الإلزامي'\)\}'\)/g, "translateInline(lang, 'Android Biometric Prompt • Mandatory Biometrics', 'Android Biometric Prompt • التحقق البيومتري الإلزامي')");

fs.writeFileSync('src/components/AntiUninstallProtectionCard.tsx', text);
